version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - 5173:5173
    volumes:
      - ".:/app"
      - "/app/node_modules"
